-- Rotterdam Investment Priority Lab
-- Generated from the published indicator definitions and default scenario: Balanced investment.
-- Ties use average rank. A single valid observation scores 50.
-- Invalid values stay missing. Available weights are renormalized, confidence uses all weights.
-- Source query defines the geographic/year extent. Preserve geometry and raw fields.
WITH
source AS (SELECT * FROM ST_Read('https://api.pdok.nl/cbs/vierkantstatistieken500m/ogc/v1/collections/vierkant500/items?f=json&bbox=4.40,51.87,4.60,51.99&limit=1000&filter=jaarcode%20%3D%202024&filter-lang=cql2-text')),
base AS (SELECT row_number() OVER () AS _row_id, *,
  CASE WHEN (TRY_CAST("aantal_inwoners" AS DOUBLE)) IS NOT NULL AND (TRY_CAST("aantal_inwoners" AS DOUBLE)) >= 0 THEN TRY_CAST("aantal_inwoners" AS DOUBLE) END AS value_0,
  CASE WHEN (CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END) IS NOT NULL AND (CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END) >= 0 THEN CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_inwoners_65_jaar_en_ouder" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END END AS value_1,
  CASE WHEN (TRY_CAST("percentage_laag_inkomen_huishouden" AS DOUBLE)) IS NOT NULL AND (TRY_CAST("percentage_laag_inkomen_huishouden" AS DOUBLE)) >= 0 AND (TRY_CAST("percentage_laag_inkomen_huishouden" AS DOUBLE)) <= 100 THEN TRY_CAST("percentage_laag_inkomen_huishouden" AS DOUBLE) END AS value_2,
  CASE WHEN (CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END) IS NOT NULL AND (CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END) >= 0 THEN CASE WHEN TRY_CAST("aantal_inwoners" AS DOUBLE) > 0 AND TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) >= 0 THEN TRY_CAST("aantal_personen_met_uitkering_onder_aowlft" AS DOUBLE) / TRY_CAST("aantal_inwoners" AS DOUBLE) * 100 END END AS value_3,
  CASE WHEN (TRY_CAST("dichtstbijzijnde_huisartsenpraktijk_afstand_in_km" AS DOUBLE)) IS NOT NULL AND (TRY_CAST("dichtstbijzijnde_huisartsenpraktijk_afstand_in_km" AS DOUBLE)) >= 0 THEN TRY_CAST("dichtstbijzijnde_huisartsenpraktijk_afstand_in_km" AS DOUBLE) END AS value_4,
  CASE WHEN (TRY_CAST("dichtstbijzijnde_basisonderwijs_afstand_in_km" AS DOUBLE)) IS NOT NULL AND (TRY_CAST("dichtstbijzijnde_basisonderwijs_afstand_in_km" AS DOUBLE)) >= 0 THEN TRY_CAST("dichtstbijzijnde_basisonderwijs_afstand_in_km" AS DOUBLE) END AS value_5,
  CASE WHEN (TRY_CAST("dichtstbijzijnde_grote_supermarkt_afstand_in_km" AS DOUBLE)) IS NOT NULL AND (TRY_CAST("dichtstbijzijnde_grote_supermarkt_afstand_in_km" AS DOUBLE)) >= 0 THEN TRY_CAST("dichtstbijzijnde_grote_supermarkt_afstand_in_km" AS DOUBLE) END AS value_6 FROM source),
rank_0 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_0) - 1 + (count(*) OVER (PARTITION BY value_0) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_0 IS NOT NULL),
rank_1 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_1) - 1 + (count(*) OVER (PARTITION BY value_1) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_1 IS NOT NULL),
rank_2 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_2) - 1 + (count(*) OVER (PARTITION BY value_2) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_2 IS NOT NULL),
rank_3 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_3) - 1 + (count(*) OVER (PARTITION BY value_3) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_3 IS NOT NULL),
rank_4 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_4) - 1 + (count(*) OVER (PARTITION BY value_4) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_4 IS NOT NULL),
rank_5 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_5) - 1 + (count(*) OVER (PARTITION BY value_5) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_5 IS NOT NULL),
rank_6 AS (SELECT _row_id, CASE WHEN count(*) OVER () = 1 THEN 50.0 ELSE 100.0 * (rank() OVER (ORDER BY value_6) - 1 + (count(*) OVER (PARTITION BY value_6) - 1) / 2.0) / (count(*) OVER () - 1) END AS score FROM base WHERE value_6 IS NOT NULL),
result AS (SELECT b.*, round((coalesce(r0.score * 0.2, 0) + coalesce(r1.score * 0.15, 0) + coalesce(r2.score * 0.2, 0) + coalesce(r3.score * 0.15, 0) + coalesce(r4.score * 0.1, 0) + coalesce(r5.score * 0.1, 0) + coalesce(r6.score * 0.1, 0)) / nullif((CASE WHEN r0.score IS NOT NULL THEN 0.2 ELSE 0 END + CASE WHEN r1.score IS NOT NULL THEN 0.15 ELSE 0 END + CASE WHEN r2.score IS NOT NULL THEN 0.2 ELSE 0 END + CASE WHEN r3.score IS NOT NULL THEN 0.15 ELSE 0 END + CASE WHEN r4.score IS NOT NULL THEN 0.1 ELSE 0 END + CASE WHEN r5.score IS NOT NULL THEN 0.1 ELSE 0 END + CASE WHEN r6.score IS NOT NULL THEN 0.1 ELSE 0 END), 0), 1) AS priority_score, round(100.0 * (CASE WHEN r0.score IS NOT NULL THEN 0.2 ELSE 0 END + CASE WHEN r1.score IS NOT NULL THEN 0.15 ELSE 0 END + CASE WHEN r2.score IS NOT NULL THEN 0.2 ELSE 0 END + CASE WHEN r3.score IS NOT NULL THEN 0.15 ELSE 0 END + CASE WHEN r4.score IS NOT NULL THEN 0.1 ELSE 0 END + CASE WHEN r5.score IS NOT NULL THEN 0.1 ELSE 0 END + CASE WHEN r6.score IS NOT NULL THEN 0.1 ELSE 0 END) / 1, 1) AS confidence FROM base b
LEFT JOIN rank_0 r0 USING (_row_id)
LEFT JOIN rank_1 r1 USING (_row_id)
LEFT JOIN rank_2 r2 USING (_row_id)
LEFT JOIN rank_3 r3 USING (_row_id)
LEFT JOIN rank_4 r4 USING (_row_id)
LEFT JOIN rank_5 r5 USING (_row_id)
LEFT JOIN rank_6 r6 USING (_row_id))
SELECT * FROM result ORDER BY priority_score DESC NULLS LAST;
